import { Inter } from "next/font/google";
import "./globals.css";
import AuthContext from "@/Context/AuthContext";
import ContextApi from "@/Context/ContextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextApi>
          <AuthContext>{children}</AuthContext>
        </ContextApi>
      </body>
    </html>
  );
}
